# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e9b0e1dd5dcdb995dc1b24c2faf6313f4e408c51b4a9bc78d26905ecc3fa2b6d07c219eae1f325899cac10b367eb98092779721afb0bb94621ef22afb68a5f

test:
  secret_key_base: 414fe78a1f8506ae4126a3f73040bb057d550490d06eb8ae254e7417d96da73527054e58dc9542b319146ade2c961c2046148f2419368dc616e0512dba90eae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
